seed: 0
mixed_precision: True
base_lr: 2.0e-4
use_cosine_annealing_warmup_lr: True

nr_gpus: 8
batch_size: 2
n_total_epoch: 600
minibatch_per_epoch: 20

loadmodel: ~
log_dir: "./drive/MyDrive/crestereo/train_log"
model_save_freq_epoch: 50

max_disp: 256
image_width: 512
image_height: 384
training_data_path: "./stereo_dataset/ETH3D/two_view_training"

log_level: "logging.INFO"
dist: False # True for DDP, False for DP
